#!/bin/bash

# get current username
USERNAME=$(whoami)
DATETIME=$(date +"%Y%m%d/%H:%M:%S")
echo -e "System Report generated by $USERNAME $DATETIME"

# print system information
echo -e "\nSystem Information\n------------------"
echo "Hostname: $(hostname)"
echo "OS: $(awk -F= '/^PRETTY_NAME/{print $2}' /etc/os-release | tr -d '\"')"
echo "Uptime: $(uptime -p)"

# print hardware information
echo -e "\nHardware Information\n------------------"
echo "CPU: $(awk -F: '/^model name/{print $2; exit}' /proc/cpuinfo | xargs)"
echo "Speed: $(awk -F: '/^cpu MHz/{print $2; exit}' /proc/cpuinfo) MHz"
echo "Ram: $(free -h | awk '/Mem:/{print $2}')"
echo "Disks:$(lsblk -d -o MODEL,SIZE | awk 'NR>1'| grep  ^[a-zA-Z])"
echo "Video: $(lspci | grep -iE 'vga|3d|2d' | sed 's/.*: //')"

# print network information
echo -e "\nNetwork Information\n------------------"
echo "FQDN: $(hostname -f)"
echo "Host Address: $(hostname -I)"
echo "Gateway IP: $(ip r | awk '/default/ {print $3}')"
echo "DNS Server: $(awk '/^nameserver/{print $2}' /etc/resolv.conf | tr '\n' ' ')"
echo "Interface Name: $(ip link show | awk -F: '$1~/^[0-9]+$/{print $2}' | xargs)"
echo "IP Address: $(ip a show $(ip r | awk '/default/ {print $5}') | awk '/inet /{print $2}')"

# print system status
echo -e "\nSystem Status\n------------------"
echo "Users Logged In: $(who | awk '{print $1}' | sort -u | tr '\n' ',' | sed 's/,$//')"
echo "Disk Space:"
df -h | awk '{printf "%-20s  %-s\n", $6, $4}'

echo "Process Count: $(ps -e --no-headers | wc -l)"
echo "Load Averages: $(uptime | awk -F 'load average: ' '{print $2}')"
echo "Memory Allocation: $(free -h | awk '/Mem:/{print "Total: "$2,"Used: "$3,"Free: "$4}')"
echo "Listening Network Ports: $(ss -tuln | awk 'NR>1{print $4}' | cut -d: -f2 | sort -n | uniq | tr '\n' ', ' | sed 's/,$//')"
echo "UFW Rules:"
sudo ufw status | sed '2d'
